name: SodaKeyBind
version: 1.0.0
main: soda.keybind.SodaKeyBind
api-version: 1.21
authors: [Haruka]

# 新增 commands 部分
commands:
  sodakeybind:
    description: SodaKeyBind 主命令
    aliases: [skb]
    usage: /skb reload

permissions:
  soda.keybind.use:
    description: 允许使用按键绑定
    default: true
  # 新增管理权限
  soda.keybind.admin:
    description: 允许重载配置
    default: op
